export { channelRegistry } from './AdapterRegistry'
export { channelConfigStore } from './ChannelConfigRepository'
export { channelSecurityManager } from './MessageSecurityGuard'
export { channelErrorHandler } from './MessageErrorHandler'
export { channelService } from './MessagingService'
export { channelBridge } from './MessageBridge'
export { webhookServer } from './WebhookReceiver'
export { FeishuChannelPlugin, feishuChannelPlugin } from './adapters/FeishuChannelPlugin'
export { WechatChannelPlugin, wechatChannelPlugin } from './adapters/WechatChannelPlugin'
export { WhatsAppChannelPlugin, whatsappChannelPlugin } from './adapters/WhatsAppChannelPlugin'
