import type { WorkflowDefinition } from '@shared/types/workflow'

export const codeReviewWorkflow: WorkflowDefinition = {
  id: 'code-review',
  name: 'Code Review',
  nameZh: '代码审查',
  description: 'Analyze code quality, detect issues, and suggest improvements',
  descriptionZh: '分析代码质量，检测问题并提出改进建议',
  version: '1.0.0',
  author: 'system',
  category: 'code-review',
  tags: ['review', 'quality', 'security'],
  icon: 'Search',
  startStep: 'analyze',
  inputSchema: {
    targetFiles: {
      type: 'string',
      description: 'Files or directories to review',
      descriptionZh: '要审查的文件或目录',
      required: true,
    },
  },
  steps: {
    analyze: {
      id: 'analyze',
      name: 'Analyze Requirements',
      nameZh: '需求理解',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Analyze the following code and understand its purpose, structure, and dependencies: {{targetFiles}}',
        outputVar: 'analysis',
        waitForResponse: true,
      },
      next: 'detect',
    },
    detect: {
      id: 'detect',
      name: 'Detect Issues',
      nameZh: '问题检测',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the analysis: {{analysis}}\n\nDetect potential bugs, security vulnerabilities, performance issues, and code smells.',
        outputVar: 'issues',
        waitForResponse: true,
      },
      next: 'suggest',
    },
    suggest: {
      id: 'suggest',
      name: 'Suggest Improvements',
      nameZh: '改进建议',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the issues found: {{issues}}\n\nProvide specific, actionable improvement suggestions with code examples.',
        outputVar: 'suggestions',
        waitForResponse: true,
      },
    },
  },
}

export const featureDevWorkflow: WorkflowDefinition = {
  id: 'feature-dev',
  name: 'Feature Development',
  nameZh: '功能开发',
  description: 'End-to-end feature development from requirements to implementation',
  descriptionZh: '从需求分析到实现的端到端功能开发',
  version: '1.0.0',
  author: 'system',
  category: 'automation',
  tags: ['development', 'feature', 'implementation'],
  icon: 'Rocket',
  startStep: 'requirements',
  inputSchema: {
    featureDescription: {
      type: 'string',
      description: 'Description of the feature to develop',
      descriptionZh: '要开发的功能描述',
      required: true,
    },
  },
  steps: {
    requirements: {
      id: 'requirements',
      name: 'Requirements Analysis',
      nameZh: '需求分析',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Analyze the following feature request and break it down into detailed requirements:\n\n{{featureDescription}}',
        outputVar: 'requirements',
        waitForResponse: true,
      },
      next: 'design',
    },
    design: {
      id: 'design',
      name: 'Architecture Design',
      nameZh: '架构设计',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the requirements:\n{{requirements}}\n\nDesign the architecture: identify files to create/modify, data structures, APIs, and component relationships.',
        outputVar: 'design',
        waitForResponse: true,
      },
      next: 'implement',
    },
    implement: {
      id: 'implement',
      name: 'Implementation',
      nameZh: '编码实现',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the design:\n{{design}}\n\nImplement the feature. Write clean, well-structured code following project conventions.',
        outputVar: 'implementation',
        waitForResponse: true,
      },
      next: 'verify',
    },
    verify: {
      id: 'verify',
      name: 'Self-Test & Fix',
      nameZh: '自测修复',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Review the implementation:\n{{implementation}}\n\nCheck for bugs, missing error handling, and edge cases. Fix any issues found.',
        outputVar: 'verification',
        waitForResponse: true,
      },
    },
  },
}

export const refactorWorkflow: WorkflowDefinition = {
  id: 'refactor-migration',
  name: 'Refactor & Migration',
  nameZh: '重构迁移',
  description: 'Systematic refactoring with impact analysis and verification',
  descriptionZh: '系统化重构，包含影响分析和验证',
  version: '1.0.0',
  author: 'system',
  category: 'automation',
  tags: ['refactor', 'migration', 'restructure'],
  icon: 'RefreshCw',
  startStep: 'impact',
  inputSchema: {
    refactorTarget: {
      type: 'string',
      description: 'What to refactor or migrate',
      descriptionZh: '要重构或迁移的目标',
      required: true,
    },
  },
  steps: {
    impact: {
      id: 'impact',
      name: 'Impact Analysis',
      nameZh: '影响分析',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Analyze the impact of the following refactoring:\n\n{{refactorTarget}}\n\nIdentify all affected files, dependencies, and potential risks.',
        outputVar: 'impactAnalysis',
        waitForResponse: true,
      },
      next: 'plan',
    },
    plan: {
      id: 'plan',
      name: 'Refactoring Plan',
      nameZh: '重构方案',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the impact analysis:\n{{impactAnalysis}}\n\nCreate a step-by-step refactoring plan with safe incremental changes.',
        outputVar: 'plan',
        waitForResponse: true,
      },
      next: 'execute',
    },
    execute: {
      id: 'execute',
      name: 'Step-by-Step Refactor',
      nameZh: '逐步重构',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Execute the refactoring plan step by step:\n{{plan}}\n\nApply each change carefully, ensuring the code remains functional after each step.',
        outputVar: 'execution',
        waitForResponse: true,
      },
      next: 'validate',
    },
    validate: {
      id: 'validate',
      name: 'Validation & Testing',
      nameZh: '验证测试',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Validate the refactoring results:\n{{execution}}\n\nVerify that all changes are correct, no functionality is broken, and the code is cleaner.',
        outputVar: 'validation',
        waitForResponse: true,
      },
    },
  },
}

export const docGenWorkflow: WorkflowDefinition = {
  id: 'doc-generation',
  name: 'Documentation Generation',
  nameZh: '文档生成',
  description: 'Generate comprehensive documentation from code',
  descriptionZh: '从代码生成全面的文档',
  version: '1.0.0',
  author: 'system',
  category: 'documentation',
  tags: ['documentation', 'api', 'readme'],
  icon: 'FileText',
  startStep: 'analyze-code',
  inputSchema: {
    targetPath: {
      type: 'string',
      description: 'Code path to document',
      descriptionZh: '要生成文档的代码路径',
      required: true,
    },
  },
  steps: {
    'analyze-code': {
      id: 'analyze-code',
      name: 'Code Analysis',
      nameZh: '代码分析',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Analyze the codebase at: {{targetPath}}\n\nIdentify all public APIs, classes, functions, and their relationships.',
        outputVar: 'codeAnalysis',
        waitForResponse: true,
      },
      next: 'write-docs',
    },
    'write-docs': {
      id: 'write-docs',
      name: 'Write Documentation',
      nameZh: '编写文档',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the code analysis:\n{{codeAnalysis}}\n\nWrite comprehensive documentation including API reference, usage examples, and configuration guide.',
        outputVar: 'documentation',
        waitForResponse: true,
      },
      next: 'examples',
    },
    examples: {
      id: 'examples',
      name: 'Generate Examples',
      nameZh: '示例生成',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the documentation:\n{{documentation}}\n\nCreate practical code examples and usage scenarios.',
        outputVar: 'examples',
        waitForResponse: true,
      },
    },
  },
}

export const bugFixWorkflow: WorkflowDefinition = {
  id: 'bug-fix',
  name: 'Bug Fix',
  nameZh: 'Bug 修复',
  description: 'Systematic bug reproduction, root cause analysis, and fix',
  descriptionZh: '系统化的 Bug 复现、根因分析和修复',
  version: '1.0.0',
  author: 'system',
  category: 'automation',
  tags: ['bug', 'fix', 'debug'],
  icon: 'Bug',
  startStep: 'reproduce',
  inputSchema: {
    bugDescription: {
      type: 'string',
      description: 'Description of the bug',
      descriptionZh: 'Bug 描述',
      required: true,
    },
  },
  steps: {
    reproduce: {
      id: 'reproduce',
      name: 'Reproduce Issue',
      nameZh: '问题复现',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Analyze the following bug report and identify reproduction steps:\n\n{{bugDescription}}',
        outputVar: 'reproduction',
        waitForResponse: true,
      },
      next: 'root-cause',
    },
    'root-cause': {
      id: 'root-cause',
      name: 'Root Cause Analysis',
      nameZh: '根因分析',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the reproduction steps:\n{{reproduction}}\n\nTrace through the code to find the root cause of the bug.',
        outputVar: 'rootCause',
        waitForResponse: true,
      },
      next: 'fix',
    },
    fix: {
      id: 'fix',
      name: 'Implement Fix',
      nameZh: '修复方案',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Based on the root cause:\n{{rootCause}}\n\nImplement a fix that addresses the root cause without introducing new issues.',
        outputVar: 'fixResult',
        waitForResponse: true,
      },
      next: 'verify-fix',
    },
    'verify-fix': {
      id: 'verify-fix',
      name: 'Verify Fix',
      nameZh: '验证修复',
      type: 'agent_message',
      config: {
        type: 'agent_message',
        message: 'Verify the fix:\n{{fixResult}}\n\nEnsure the original bug is fixed and no regressions are introduced.',
        outputVar: 'verification',
        waitForResponse: true,
      },
    },
  },
}

export const builtinWorkflows: WorkflowDefinition[] = [
  codeReviewWorkflow,
  featureDevWorkflow,
  refactorWorkflow,
  docGenWorkflow,
  bugFixWorkflow,
]
