import type { WorkflowDefinition } from '@shared/protocols/workflow'

export const codeReviewWorkflow: WorkflowDefinition = {
  id: 'code-review',
  name: 'Code Review',
  nameZh: '代码审查',
  description: 'Multi-agent code review: analyst reviews code, reviewer checks quality, then suggests improvements',
  descriptionZh: '多智体代码审查：分析师审查代码，审查员检查质量，然后提出改进建议',
  version: '1.0.0',
  author: 'system',
  category: 'code-review',
  tags: ['review', 'quality', 'security'],
  icon: 'Search',
  startStep: 'analyze',
  inputSchema: {
    targetFiles: {
      type: 'string',
      description: 'Files or directories to review',
      descriptionZh: '要审查的文件或目录',
      required: true,
    },
  },
  steps: {
    analyze: {
      id: 'analyze',
      name: 'Code Analysis',
      nameZh: '代码分析',
      type: 'agent_message',
      roleId: 'analyst',
      config: {
        type: 'agent_message',
        message: 'Analyze the following code and understand its purpose, structure, and dependencies: {{targetFiles}}',
        outputVar: 'analysis',
        waitForResponse: true,
      },
      next: 'review',
    },
    review: {
      id: 'review',
      name: 'Quality Review',
      nameZh: '质量审查',
      type: 'agent_message',
      roleId: 'reviewer',
      config: {
        type: 'agent_message',
        message: 'Based on the analysis: {{analysis}}\n\nReview the code for quality issues, security vulnerabilities, performance problems, and best practice violations.',
        outputVar: 'reviewResult',
        waitForResponse: true,
      },
      next: 'approve',
    },
    approve: {
      id: 'approve',
      name: 'Human Approval',
      nameZh: '人工审批',
      type: 'user_input',
      config: {
        type: 'user_input',
        prompt: 'Review the analysis and decide whether to proceed with improvements:',
        outputVar: 'approval',
        approvalMode: true,
      },
      next: 'suggest',
    },
    suggest: {
      id: 'suggest',
      name: 'Suggest Improvements',
      nameZh: '改进建议',
      type: 'agent_message',
      roleId: 'developer',
      config: {
        type: 'agent_message',
        message: 'Based on the review: {{reviewResult}}\n\nProvide specific, actionable improvement suggestions and implement the fixes.',
        outputVar: 'suggestions',
        waitForResponse: true,
      },
    },
  },
}

export const featureDevWorkflow: WorkflowDefinition = {
  id: 'feature-dev',
  name: 'Feature Development',
  nameZh: '功能开发',
  description: 'End-to-end feature development: analyst → architect → developer → reviewer',
  descriptionZh: '端到端功能开发：需求分析师 → 架构师 → 开发工程师 → 审查员',
  version: '1.0.0',
  author: 'system',
  category: 'development',
  tags: ['development', 'feature', 'implementation'],
  icon: 'Rocket',
  startStep: 'requirements',
  inputSchema: {
    featureDescription: {
      type: 'string',
      description: 'Description of the feature to develop',
      descriptionZh: '要开发的功能描述',
      required: true,
    },
  },
  steps: {
    requirements: {
      id: 'requirements',
      name: 'Requirements Analysis',
      nameZh: '需求分析',
      type: 'agent_message',
      roleId: 'analyst',
      config: {
        type: 'agent_message',
        message: 'Analyze the following feature request and break it down into detailed requirements:\n\n{{featureDescription}}',
        outputVar: 'requirements',
        waitForResponse: true,
      },
      next: 'design',
    },
    design: {
      id: 'design',
      name: 'Architecture Design',
      nameZh: '架构设计',
      type: 'agent_message',
      roleId: 'architect',
      config: {
        type: 'agent_message',
        message: 'Based on the requirements:\n{{requirements}}\n\nDesign the architecture: identify files to create/modify, data structures, APIs, and component relationships.',
        outputVar: 'design',
        waitForResponse: true,
      },
      next: 'approve-design',
    },
    'approve-design': {
      id: 'approve-design',
      name: 'Approve Design',
      nameZh: '审批方案',
      type: 'user_input',
      config: {
        type: 'user_input',
        prompt: 'Review the architecture design and approve to proceed with implementation:',
        outputVar: 'designApproval',
        approvalMode: true,
      },
      next: 'implement',
    },
    implement: {
      id: 'implement',
      name: 'Implementation',
      nameZh: '编码实现',
      type: 'agent_message',
      roleId: 'developer',
      config: {
        type: 'agent_message',
        message: 'Based on the design:\n{{design}}\n\nImplement the feature. Write clean, well-structured code following project conventions.',
        outputVar: 'implementation',
        waitForResponse: true,
      },
      next: 'review',
    },
    review: {
      id: 'review',
      name: 'Code Review',
      nameZh: '代码审查',
      type: 'agent_message',
      roleId: 'reviewer',
      config: {
        type: 'agent_message',
        message: 'Review the implementation:\n{{implementation}}\n\nCheck for bugs, security issues, performance problems, and best practice violations.',
        outputVar: 'reviewResult',
        waitForResponse: true,
      },
    },
  },
}

export const bugFixWorkflow: WorkflowDefinition = {
  id: 'bug-fix',
  name: 'Bug Fix',
  nameZh: 'Bug 修复',
  description: 'Systematic bug fix: analyst reproduces, developer fixes, reviewer verifies',
  descriptionZh: '系统化 Bug 修复：分析师复现问题，开发工程师修复，审查员验证',
  version: '1.0.0',
  author: 'system',
  category: 'development',
  tags: ['bug', 'fix', 'debug'],
  icon: 'Bug',
  startStep: 'reproduce',
  inputSchema: {
    bugDescription: {
      type: 'string',
      description: 'Description of the bug',
      descriptionZh: 'Bug 描述',
      required: true,
    },
  },
  steps: {
    reproduce: {
      id: 'reproduce',
      name: 'Reproduce & Analyze',
      nameZh: '复现与分析',
      type: 'agent_message',
      roleId: 'analyst',
      config: {
        type: 'agent_message',
        message: 'Analyze the following bug report and identify reproduction steps and root cause:\n\n{{bugDescription}}',
        outputVar: 'analysis',
        waitForResponse: true,
      },
      next: 'fix',
    },
    fix: {
      id: 'fix',
      name: 'Implement Fix',
      nameZh: '修复实现',
      type: 'agent_message',
      roleId: 'developer',
      config: {
        type: 'agent_message',
        message: 'Based on the analysis:\n{{analysis}}\n\nImplement a fix that addresses the root cause without introducing new issues.',
        outputVar: 'fixResult',
        waitForResponse: true,
      },
      next: 'verify',
    },
    verify: {
      id: 'verify',
      name: 'Verify Fix',
      nameZh: '验证修复',
      type: 'agent_message',
      roleId: 'reviewer',
      config: {
        type: 'agent_message',
        message: 'Verify the fix:\n{{fixResult}}\n\nEnsure the original bug is fixed and no regressions are introduced.',
        outputVar: 'verification',
        waitForResponse: true,
      },
    },
  },
}

export const docGenWorkflow: WorkflowDefinition = {
  id: 'doc-generation',
  name: 'Documentation Generation',
  nameZh: '文档生成',
  description: 'Generate documentation: analyst analyzes code, doc-writer creates docs',
  descriptionZh: '生成文档：分析师分析代码，文档工程师创建文档',
  version: '1.0.0',
  author: 'system',
  category: 'documentation',
  tags: ['documentation', 'api', 'readme'],
  icon: 'FileText',
  startStep: 'analyze-code',
  inputSchema: {
    targetPath: {
      type: 'string',
      description: 'Code path to document',
      descriptionZh: '要生成文档的代码路径',
      required: true,
    },
  },
  steps: {
    'analyze-code': {
      id: 'analyze-code',
      name: 'Code Analysis',
      nameZh: '代码分析',
      type: 'agent_message',
      roleId: 'analyst',
      config: {
        type: 'agent_message',
        message: 'Analyze the codebase at: {{targetPath}}\n\nIdentify all public APIs, classes, functions, and their relationships.',
        outputVar: 'codeAnalysis',
        waitForResponse: true,
      },
      next: 'write-docs',
    },
    'write-docs': {
      id: 'write-docs',
      name: 'Write Documentation',
      nameZh: '编写文档',
      type: 'agent_message',
      roleId: 'doc-writer',
      config: {
        type: 'agent_message',
        message: 'Based on the code analysis:\n{{codeAnalysis}}\n\nWrite comprehensive documentation including API reference, usage examples, and configuration guide.',
        outputVar: 'documentation',
        waitForResponse: true,
      },
    },
  },
}

export const builtinWorkflows: WorkflowDefinition[] = [
  codeReviewWorkflow,
  featureDevWorkflow,
  bugFixWorkflow,
  docGenWorkflow,
]
